stages:
  - build
  - test

build:phive:
  stage: build
  image: in2code/php:7.4-fpm
  interruptible: true
  script:
    - phive install --trust-gpg-keys 31C7E470E2138192,A4E55EA12C7C085C
  artifacts:
    paths:
      - .project/phars

test:phpcs:
  stage: test
  image: in2code/php:7.4-fpm
  interruptible: true
  script:
    - .project/phars/phpcs
  needs:
    - job: build:phive
      artifacts: true

test:phpmd:
  stage: test
  image: in2code/php:7.4-fpm
  interruptible: true
  script:
    - .project/phars/phpmd Classes ansi .phpmd.xml
  needs:
    - job: build:phive
      artifacts: true

test:phpunit:
  stage: test
  image: docker:20.10.20
  services:
    - docker:20.10.20-dind
  interruptible: true
  parallel:
    matrix:
      - PHP_VERSION: [ "8.1", "8.2" ]
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${PHP_VERSION}
    paths:
      - .Build/.cache/
  before_script:
    - apk add bash
    - Build/Scripts/runTests.sh -p $PHP_VERSION -s composerUpdate
  script:
    - Build/Scripts/runTests.sh -p $PHP_VERSION -s unit
  needs: []

test:lint:composer:
  stage: test
  image: in2code/php:7.2-fpm
  interruptible: true
  script:
    - composer validate --strict
  needs: []

test:lint:typoscript:
  stage: test
  image: in2code/typo3-typoscript-lint:7.2
  interruptible: true
  script:
    - typoscript-lint -c .typoscript-lint.yml
  needs: []

test:lint:php-8.1:
  stage: test
  image: php:8.1-cli
  interruptible: true
  script:
    - find ./ -path ./.Build -prune -false -o -type f -name '*.php' -print0 | xargs -0 -n1 -P$(nproc) php -l -n > /dev/null
  needs: []

test:lint:php-8.2:
  stage: test
  image: php:8.2-cli
  interruptible: true
  script:
    - find ./ -path ./.Build -prune -false -o -type f -name '*.php' -print0 | xargs -0 -n1 -P$(nproc) php -l -n > /dev/null
  needs: []
