stages:
  - test

test:lint:composer:
  stage: test
  image: in2code/php:7.0-fpm
  script:
    - composer validate --strict

test:lint:php-7.4:
  stage: test
  image: in2code/php-parallel-lint:7.4
  script:
    - parallel-lint Classes/

test:phpcs:
  stage: test
  image: in2code/phpcs:7.2
  script:
    - phpcs

test:phpmd:
  stage: test
  image: in2code/phpmd:7.2
  script:
    - phpmd Classes ansi .phpmd.xml

test:lint:typoscript:
  stage: test
  image: in2code/typo3-typoscript-lint:7.2
  script:
    - typoscript-lint -c .typoscript-lint.yml
